=== Okenlyzavals/ApplianceFinder/src/main/resources/appliances.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name = "appliances">
        <xs:complexType>
            <xs:all minOccurs="1" maxOccurs="1">
                <xs:element name="Oven_catalogue" type="Oven_catalogue"/>
                <xs:element name="Laptop_catalogue" type="Laptop_catalogue"/>
                <xs:element name="Refrigerator_catalogue" type="Refrigerator_catalogue"/>
                <xs:element name="VacuumCleaner_catalogue" type="VacuumCleaner_catalogue"/>
                <xs:element name="TabletPC_catalogue" type="TabletPC_catalogue"/>
                <xs:element name="Speakers_catalogue" type="Speakers_catalogue"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name = "Oven_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Oven" type="Oven"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Oven">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="POWER_CONSUMPTION" type="xs:integer" />
            <xs:element name="CAPACITY" type="xs:double" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "Laptop_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Laptop" type="Laptop"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Laptop">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="DISPLAY_INCHES" type="xs:double" />
            <xs:element name="BATTERY_CAPACITY" type="xs:double" />
            <xs:element name="OS" type="xs:string" />
            <xs:element name="MEMORY_ROM" type="xs:integer" />
            <xs:element name="SYSTEM_MEMORY" type="xs:integer" />
            <xs:element name="CPU" type="xs:double" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "Refrigerator_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Refrigerator" type="Refrigerator"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Refrigerator">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="POWER_CONSUMPTION" type="xs:integer" />
            <xs:element name="FREEZER_CAPACITY" type="xs:double" />
            <xs:element name="OVERALL_CAPACITY" type="xs:double" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "VacuumCleaner_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="VacuumCleaner" type="VacuumCleaner"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VacuumCleaner">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="POWER_CONSUMPTION" type="xs:integer" />
            <xs:element name="FILTER_TYPE" type="xs:string" />
            <xs:element name="BAG_TYPE" type="xs:string" />
            <xs:element name="WAND_TYPE" type="xs:string" />
            <xs:element name="MOTOR_SPEED_REGULATION" type="xs:integer" />
            <xs:element name="CLEANING_WIDTH" type="xs:double" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "TabletPC_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="TabletPC" type="TabletPC"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TabletPC">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="DISPLAY_INCHES" type="xs:double" />
            <xs:element name="BATTERY_CAPACITY" type="xs:double" />
            <xs:element name="MEMORY_ROM" type="xs:integer" />
            <xs:element name="FLASH_MEMORY_CAPACITY" type="xs:double" />
            <xs:element name="COLOR" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name = "Speakers_catalogue">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Speakers" type="Speakers"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Speakers">
        <xs:sequence maxOccurs="1">
            <xs:element name="WEIGHT" type="xs:double" />
            <xs:element name="WIDTH" type="xs:double" />
            <xs:element name="HEIGHT" type="xs:double" />
            <xs:element name="DEPTH" type="xs:double" />
            <xs:element name="POWER_CONSUMPTION" type="xs:integer" />
            <xs:element name="NUMBER_OF_SPEAKERS" type="xs:integer" />
            <xs:element name="MINIMAL_FREQUENCY" type="xs:double" />
            <xs:element name="MAXIMAL_FREQUENCY" type="xs:double" />
            <xs:element name="CORD_LENGTH" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Okenlyzavals/ApplianceFinder/src/main/resources/appliances.xml
<?xml version="1.0" encoding="UTF-8" ?>
<appliances xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="appliances.xsd">

    <Oven_catalogue>
        <Oven>
            <WEIGHT>8</WEIGHT>
            <WIDTH>59.5</WIDTH>
            <HEIGHT>45.5</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>1000</POWER_CONSUMPTION>
            <CAPACITY>33</CAPACITY>
        </Oven>
        <Oven>
            <WEIGHT>12</WEIGHT>
            <WIDTH>68</WIDTH>
            <HEIGHT>45</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>1500</POWER_CONSUMPTION>
            <CAPACITY>31</CAPACITY>
        </Oven>
        <Oven>
            <WEIGHT>18</WEIGHT>
            <WIDTH>70</WIDTH>
            <HEIGHT>40</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>2000</POWER_CONSUMPTION>
            <CAPACITY>36</CAPACITY>
        </Oven>
    </Oven_catalogue>

    <Laptop_catalogue>
        <Laptop>
            <WEIGHT>2.4</WEIGHT>
            <WIDTH>50</WIDTH>
            <HEIGHT>30</HEIGHT>
            <DEPTH>4</DEPTH>
            <DISPLAY_INCHES>18</DISPLAY_INCHES>
            <BATTERY_CAPACITY>1</BATTERY_CAPACITY>
            <OS>Windows</OS>
            <MEMORY_ROM>4000</MEMORY_ROM>
            <SYSTEM_MEMORY>1000</SYSTEM_MEMORY>
            <CPU>1.2</CPU>
        </Laptop>
        <Laptop>
            <WEIGHT>2.4</WEIGHT>
            <WIDTH>50</WIDTH>
            <HEIGHT>35</HEIGHT>
            <DEPTH>3</DEPTH>
            <DISPLAY_INCHES>19</DISPLAY_INCHES>
            <BATTERY_CAPACITY>1.5</BATTERY_CAPACITY>
            <OS>Linux</OS>
            <MEMORY_ROM>8000</MEMORY_ROM>
            <SYSTEM_MEMORY>1000</SYSTEM_MEMORY>
            <CPU>2.2</CPU>
        </Laptop>
        <Laptop>
            <WEIGHT>2.4</WEIGHT>
            <WIDTH>56</WIDTH>
            <HEIGHT>36</HEIGHT>
            <DEPTH>4</DEPTH>
            <DISPLAY_INCHES>22</DISPLAY_INCHES>
            <BATTERY_CAPACITY>3</BATTERY_CAPACITY>
            <OS>Windows</OS>
            <MEMORY_ROM>8000</MEMORY_ROM>
            <SYSTEM_MEMORY>1500</SYSTEM_MEMORY>
            <CPU>3.2</CPU>
        </Laptop>
    </Laptop_catalogue>

    <Refrigerator_catalogue>
        <Refrigerator>
            <WEIGHT>20</WEIGHT>
            <WIDTH>70</WIDTH>
            <HEIGHT>200</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>100</POWER_CONSUMPTION>
            <FREEZER_CAPACITY>10</FREEZER_CAPACITY>
            <OVERALL_CAPACITY>300</OVERALL_CAPACITY>
        </Refrigerator>
        <Refrigerator>
            <WEIGHT>30</WEIGHT>
            <WIDTH>80</WIDTH>
            <HEIGHT>180</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>200</POWER_CONSUMPTION>
            <FREEZER_CAPACITY>15</FREEZER_CAPACITY>
            <OVERALL_CAPACITY>300</OVERALL_CAPACITY>
        </Refrigerator>
        <Refrigerator>
            <WEIGHT>35</WEIGHT>
            <WIDTH>75</WIDTH>
            <HEIGHT>250</HEIGHT>
            <DEPTH>60</DEPTH>
            <POWER_CONSUMPTION>150</POWER_CONSUMPTION>
            <FREEZER_CAPACITY>20</FREEZER_CAPACITY>
            <OVERALL_CAPACITY>350.5</OVERALL_CAPACITY>
        </Refrigerator>
    </Refrigerator_catalogue>

    <VacuumCleaner_catalogue>
        <VacuumCleaner>
            <WEIGHT>15</WEIGHT>
            <WIDTH>40</WIDTH>
            <HEIGHT>50</HEIGHT>
            <DEPTH>70</DEPTH>
            <POWER_CONSUMPTION>100</POWER_CONSUMPTION>
            <FILTER_TYPE>A</FILTER_TYPE>
            <BAG_TYPE>A2</BAG_TYPE>
            <WAND_TYPE>all-in-one</WAND_TYPE>
            <MOTOR_SPEED_REGULATION>3000</MOTOR_SPEED_REGULATION>
            <CLEANING_WIDTH>20</CLEANING_WIDTH>
        </VacuumCleaner>
        <VacuumCleaner>
            <WEIGHT>16</WEIGHT>
            <WIDTH>50</WIDTH>
            <HEIGHT>50</HEIGHT>
            <DEPTH>75</DEPTH>
            <POWER_CONSUMPTION>110</POWER_CONSUMPTION>
            <FILTER_TYPE>B</FILTER_TYPE>
            <BAG_TYPE>AA-89</BAG_TYPE>
            <WAND_TYPE>all-in-one</WAND_TYPE>
            <MOTOR_SPEED_REGULATION>2900</MOTOR_SPEED_REGULATION>
            <CLEANING_WIDTH>25</CLEANING_WIDTH>
        </VacuumCleaner>
        <VacuumCleaner>
            <WEIGHT>12</WEIGHT>
            <WIDTH>38</WIDTH>
            <HEIGHT>45</HEIGHT>
            <DEPTH>65</DEPTH>
            <POWER_CONSUMPTION>90</POWER_CONSUMPTION>
            <FILTER_TYPE>C</FILTER_TYPE>
            <BAG_TYPE>XX00</BAG_TYPE>
            <WAND_TYPE>all-in-one</WAND_TYPE>
            <MOTOR_SPEED_REGULATION>2950</MOTOR_SPEED_REGULATION>
            <CLEANING_WIDTH>30</CLEANING_WIDTH>
        </VacuumCleaner>
    </VacuumCleaner_catalogue>

    <TabletPC_catalogue>
        <TabletPC>
            <WEIGHT>0.8</WEIGHT>
            <WIDTH>32</WIDTH>
            <HEIGHT>18</HEIGHT>
            <DEPTH>0.8</DEPTH>
            <DISPLAY_INCHES>14</DISPLAY_INCHES>
            <BATTERY_CAPACITY>3</BATTERY_CAPACITY>
            <MEMORY_ROM>8000</MEMORY_ROM>
            <FLASH_MEMORY_CAPACITY>2</FLASH_MEMORY_CAPACITY>
            <COLOR>blue</COLOR>
        </TabletPC>
        <TabletPC>
            <WEIGHT>0.9</WEIGHT>
            <WIDTH>36</WIDTH>
            <HEIGHT>20.25</HEIGHT>
            <DEPTH>0.8</DEPTH>
            <DISPLAY_INCHES>15</DISPLAY_INCHES>
            <BATTERY_CAPACITY>4</BATTERY_CAPACITY>
            <MEMORY_ROM>8000</MEMORY_ROM>
            <FLASH_MEMORY_CAPACITY>6</FLASH_MEMORY_CAPACITY>
            <COLOR>red</COLOR>
        </TabletPC>
        <TabletPC>
            <WEIGHT>1</WEIGHT>
            <WIDTH>36</WIDTH>
            <HEIGHT>20.25</HEIGHT>
            <DEPTH>0.8</DEPTH>
            <DISPLAY_INCHES>16</DISPLAY_INCHES>
            <BATTERY_CAPACITY>5</BATTERY_CAPACITY>
            <MEMORY_ROM>16000</MEMORY_ROM>
            <FLASH_MEMORY_CAPACITY>8</FLASH_MEMORY_CAPACITY>
            <COLOR>green</COLOR>
        </TabletPC>
    </TabletPC_catalogue>

    <Speakers_catalogue>
        <Speakers>
            <WEIGHT>1</WEIGHT>
            <WIDTH>8</WIDTH>
            <HEIGHT>20</HEIGHT>
            <DEPTH>8</DEPTH>
            <POWER_CONSUMPTION>15</POWER_CONSUMPTION>
            <NUMBER_OF_SPEAKERS>2</NUMBER_OF_SPEAKERS>
            <MINIMAL_FREQUENCY>2</MINIMAL_FREQUENCY>
            <MAXIMAL_FREQUENCY>4</MAXIMAL_FREQUENCY>
            <CORD_LENGTH>2</CORD_LENGTH>
        </Speakers>
        <Speakers>
            <WEIGHT>1</WEIGHT>
            <WIDTH>8</WIDTH>
            <HEIGHT>20</HEIGHT>
            <DEPTH>8</DEPTH>
            <POWER_CONSUMPTION>20</POWER_CONSUMPTION>
            <NUMBER_OF_SPEAKERS>3</NUMBER_OF_SPEAKERS>
            <MINIMAL_FREQUENCY>2</MINIMAL_FREQUENCY>
            <MAXIMAL_FREQUENCY>4</MAXIMAL_FREQUENCY>
            <CORD_LENGTH>3</CORD_LENGTH>
        </Speakers>
        <Speakers>
            <WEIGHT>1</WEIGHT>
            <WIDTH>8</WIDTH>
            <HEIGHT>20</HEIGHT>
            <DEPTH>8</DEPTH>
            <POWER_CONSUMPTION>17</POWER_CONSUMPTION>
            <NUMBER_OF_SPEAKERS>4</NUMBER_OF_SPEAKERS>
            <MINIMAL_FREQUENCY>2</MINIMAL_FREQUENCY>
            <MAXIMAL_FREQUENCY>3.5</MAXIMAL_FREQUENCY>
            <CORD_LENGTH>4</CORD_LENGTH>
        </Speakers>
    </Speakers_catalogue>

</appliances>
